#!/usr/bin/env bash
# install and configure HAproxy on load balancer server

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo apt-get -y install software-properties-common
sudo apt-get -y update

config="\
frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 326136-web-01 100.26.121.95:80 check
        server 326136-web-02 75.101.229.136:80 check
"
echo "$config" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

service haproxy restart
